"""A double-clickable ``twitchbar.app`` for macOS: a thin launcher around the installed command.

The bundle holds an icon, an Info.plist and a small shell script that launches twitchbar
    as a detached background process.
It is generated on the user's machine, so it carries no quarantine flag and Finder opens it
without a Gatekeeper prompt.
"""

from __future__ import annotations

import os
import plistlib
import shutil
import stat
import sys
from importlib import resources
from pathlib import Path

from twitchbar import __version__

APP_NAME = "twitchbar.app"
BUNDLE_ID = "io.github.artod.twitchbar.launcher"
ICON_FILE = "twitchbar.icns"


def default_location() -> Path:
    """``/Applications`` when the user may write there, otherwise ``~/Applications``."""
    system = Path("/Applications")
    return system if os.access(system, os.W_OK) else Path.home() / "Applications"


def command() -> str:
    """Absolute path of the installed ``twitchbar`` command the launcher will run."""
    found = shutil.which("twitchbar")
    if found:
        return str(Path(found).resolve())
    return f'"{sys.executable}" -m twitchbar'


def build(location: Path) -> Path:
    """Write (or refresh) ``location/twitchbar.app`` and return its path."""
    app = location / APP_NAME
    contents = app / "Contents"
    macos = contents / "MacOS"
    res = contents / "Resources"
    macos.mkdir(parents=True, exist_ok=True)
    res.mkdir(parents=True, exist_ok=True)
    plist = {
        "CFBundleName": "twitchbar",
        "CFBundleDisplayName": "twitchbar",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "twitchbar",
        "CFBundleIconFile": ICON_FILE,
        "CFBundlePackageType": "APPL",
        "CFBundleVersion": __version__,
        "CFBundleShortVersionString": __version__,
        "LSUIElement": True,
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
    }
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)
    icon = resources.files("twitchbar").joinpath("assets", ICON_FILE)
    (res / ICON_FILE).write_bytes(icon.read_bytes())
    launcher = macos / "twitchbar"
    launcher.write_text(
        "#!/bin/sh\n"
        "# Generated by `twitchbar install-app`; re-run it after reinstalling twitchbar.\n"
        "# Detach a plain background process instead of being the app's own executable: run\n"
        "# directly by LaunchServices, a rumps status item can fail to appear in the menu bar\n"
        "# on notched Macs; a detached child behaves like `twitchbar` started from a terminal,\n"
        "# which shows reliably.\n"
        f'/usr/bin/nohup {command()} run "$@" >/dev/null 2>&1 &\n'
    )
    launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    os.utime(app)  # Finder re-reads the bundle (and its icon) when the folder's mtime changes
    return app


def remove(location: Path) -> Path | None:
    """Delete ``location/twitchbar.app``; returns the removed path or None if it was not there."""
    app = location / APP_NAME
    if not app.exists():
        return None
    shutil.rmtree(app)
    return app
